(() => {
const STAGE=360;
const defaults={
background:{label:'Background',type:'image',src:'../assets_ready/background/ora_wf_bg_main.png',x:0,y:0,w:360,h:360,z:1,visible:true},
logo:{label:'Logo ORA',type:'image',src:'../assets_ready/logo/ora_wf_logo_header.png',x:64,y:14,w:232,h:78,z:10,visible:true},
timePanel:{label:'Time Panel',type:'image',src:'../assets_ready/panels/ora_wf_panel_time.png',x:30,y:78,w:300,h:100,z:20,visible:true},
datePanel:{label:'Date Panel',type:'image',src:'../assets_ready/panels/ora_wf_panel_date.png',x:87,y:150,w:190,h:63,z:30,visible:true},
mascot:{label:'Awan',type:'image',src:'../assets_ready/mascot/ora_wf_mascot_awan_idle_01.png',x:92,y:180,w:170,h:170,z:40,visible:true},
stepsPanel:{label:'Steps Panel',type:'image',src:'../assets_ready/panels/ora_wf_panel_steps.png',x:275,y:190,w:74,h:111,z:45,visible:true},
recoveryPanel:{label:'Recovery Panel',type:'image',src:'../assets_ready/panels/ora_wf_panel_recovery_01.png',x:275,y:253,w:74,h:111,z:46,visible:true},
bottomBar:{label:'Bottom Bar',type:'image',src:'../assets_ready/panels/ora_wf_panel_status_bottom.png',x:46,y:317,w:268,h:38,z:50,visible:true},
timeText:{label:'Time Text',type:'text',x:52,y:88,w:256,h:70,z:60,visible:true,text:'15:12',font:'Jersey10',fontSize:72,color:'#ffffff'},
dateText:{label:'Date Text',type:'text',x:95,y:164,w:170,h:28,z:61,visible:true,text:'MON 24 AUG',font:'PressStart2P',fontSize:12,color:'#ffffff'},
stepsText:{label:'Steps Value',type:'text',x:281,y:257,w:60,h:26,z:62,visible:true,text:'8123',font:'Jersey10',fontSize:28,color:'#ffffff'},
recoveryText:{label:'Recovery Value',type:'text',x:281,y:317,w:60,h:24,z:63,visible:false,text:'18 H',font:'Jersey10',fontSize:26,color:'#ffffff'},
batteryText:{label:'Battery Value',type:'text',x:165,y:327,w:52,h:22,z:64,visible:true,text:'82%',font:'Jersey10',fontSize:22,color:'#ffffff'}};
let layers=JSON.parse(JSON.stringify(defaults)),selected=null,zoom=1.3,drag=null;
const $=id=>document.getElementById(id),stage=$('stage'),scaler=$('stageScaler'),safe=$('safeCircle'),list=$('layerList'),json=$('jsonOutput');
function el(k){return $('layer-'+k)} function render(k){const l=layers[k],e=el(k);if(!e)return;e.style.left=l.x+'px';e.style.top=l.y+'px';e.style.width=l.w+'px';e.style.height=l.h+'px';e.style.zIndex=l.z;e.style.display=l.visible?'':'none';e.classList.toggle('selected',k===selected);if(l.type==='image'){if(e.dataset.src!==l.src){e.src=l.src;e.dataset.src=l.src}}else{e.textContent=l.text;e.style.fontSize=l.fontSize+'px';e.style.color=l.color;e.classList.toggle('jersey',l.font==='Jersey10');e.classList.toggle('pressstart',l.font==='PressStart2P');e.style.fontFamily=l.font==='system'?'Segoe UI,Arial,sans-serif':''}}
function controls(){if(!selected){$('selectedName').textContent='—';$('textControls').classList.add('hidden');return}const l=layers[selected];$('selectedName').textContent=l.label;$('xInput').value=l.x;$('yInput').value=l.y;$('wInput').value=l.w;$('hInput').value=l.h;if(l.type==='text'){$('textControls').classList.remove('hidden');$('textInput').value=l.text;$('fontSelect').value=l.font;$('fontSizeInput').value=l.fontSize;$('colorInput').value=l.color}else $('textControls').classList.add('hidden')}
function output(){const o={};for(const [k,l] of Object.entries(layers)){o[k]={x:Math.round(l.x),y:Math.round(l.y),w:Math.round(l.w),h:Math.round(l.h),visible:!!l.visible};if(l.type==='text')Object.assign(o[k],{text:l.text,font:l.font,fontSize:l.fontSize,color:l.color})}json.value=JSON.stringify(o,null,2)}
function all(){Object.keys(layers).forEach(render);controls();output()}
function select(k){selected=k;all()}
function buildList(){list.innerHTML='';for(const [k,l] of Object.entries(layers)){const r=document.createElement('div');r.className='layer-row';const c=document.createElement('input');c.type='checkbox';c.checked=l.visible;c.onchange=()=>{l.visible=c.checked;all()};const n=document.createElement('span');n.textContent=l.label;const b=document.createElement('button');b.textContent='Select';b.onclick=()=>select(k);r.append(c,n,b);list.appendChild(r)}}
function buildAssets(){const a=$('assetInputs');a.innerHTML='';for(const [k,l] of Object.entries(layers).filter(([,v])=>v.type==='image')){const w=document.createElement('div');w.className='asset-line';const n=document.createElement('div');n.className='name';n.textContent=l.label;const f=document.createElement('input');f.type='file';f.accept='image/*';f.onchange=()=>{const file=f.files&&f.files[0];if(!file)return;if(l._blob)URL.revokeObjectURL(l._blob);l._blob=URL.createObjectURL(file);l.src=l._blob;el(k).dataset.src='';all()};w.append(n,f);a.appendChild(w)}}
['xInput','yInput','wInput','hInput'].forEach(id=>$(id).addEventListener('input',()=>{if(!selected)return;const l=layers[selected];l.x=+$('xInput').value||0;l.y=+$('yInput').value||0;l.w=Math.max(1,+$('wInput').value||1);l.h=Math.max(1,+$('hInput').value||1);all()}));
$('textInput').oninput=()=>{if(selected&&layers[selected].type==='text'){layers[selected].text=$('textInput').value;all()}};$('fontSelect').onchange=()=>{if(selected&&layers[selected].type==='text'){layers[selected].font=$('fontSelect').value;all()}};$('fontSizeInput').oninput=()=>{if(selected&&layers[selected].type==='text'){layers[selected].fontSize=Math.max(6,+$('fontSizeInput').value||6);all()}};$('colorInput').oninput=()=>{if(selected&&layers[selected].type==='text'){layers[selected].color=$('colorInput').value;all()}};
$('centerXBtn').onclick=()=>{if(selected){layers[selected].x=Math.round((STAGE-layers[selected].w)/2);all()}};$('centerYBtn').onclick=()=>{if(selected){layers[selected].y=Math.round((STAGE-layers[selected].h)/2);all()}};
for(const k of Object.keys(layers)){const e=el(k);e.addEventListener('pointerdown',ev=>{ev.preventDefault();select(k);e.setPointerCapture(ev.pointerId);drag={k,id:ev.pointerId,sx:ev.clientX,sy:ev.clientY,x:layers[k].x,y:layers[k].y}});e.addEventListener('pointermove',ev=>{if(!drag||drag.k!==k||drag.id!==ev.pointerId)return;layers[k].x=Math.round(drag.x+(ev.clientX-drag.sx)/zoom);layers[k].y=Math.round(drag.y+(ev.clientY-drag.sy)/zoom);all()});e.addEventListener('pointerup',()=>drag=null);e.addEventListener('pointercancel',()=>drag=null)}
function setZoom(p){zoom=p/100;stage.style.transform=`scale(${zoom})`;scaler.style.width=(360*zoom)+'px';scaler.style.height=(360*zoom)+'px';$('zoomValue').textContent=p+'%'}$('zoomRange').oninput=()=>setZoom(+$('zoomRange').value);$('safeCircleToggle').onchange=e=>safe.style.display=e.target.checked?'':'none';
$('resetBtn').onclick=()=>{if(confirm('Reset semua posisi dan ukuran?')){layers=JSON.parse(JSON.stringify(defaults));selected=null;buildList();buildAssets();all()}};$('copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(json.value);alert('Layout JSON berhasil disalin.')}catch{json.focus();json.select();alert('Tekan Ctrl+C untuk menyalin JSON.')}};setZoom(130);buildList();buildAssets();all();select('timeText');
})();